name = "chumi-cron-worker"
main = "index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "*/30 * * * *",   # обычные задачи каждые 30 минут
  "5 9 * * *"       # ежедневно в 09:05 UTC — для сводки
]

